/*
 * Wazuh app - Wazuh CSV column keys
 * Copyright (C) 2015-2022 Wazuh, Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Find more information about this on the LICENSE file.
 */
export const KeyEquivalence: {[key: string]: string} = {
  id: 'ID',
  timestamp: 'Timestamp',
  url: 'URL',
  version: 'Versiyon',
  'os.name': 'OS adı',
  'os.version': 'OS versiyonu',
  'os.arch': 'OS versiyon mimarisi',
  'os.build': 'OS versiyon yapım',
  'os.codename': 'OS kod adu',
  'os.major': 'OS versiyon major',
  'os.minor': 'OS versiyon minor',
  'os.platform': 'OS platform',
  'os.uname': 'OS uname',
  status: 'Durum',
  group: 'Grup',
  ip: 'IP',
  description: 'Açıklama',
  tag: 'Tag',
  level: 'Level',
  conf_sum: 'Grup checksum',
  merged_sum: 'Konfigürasyon checksum',
  hash: 'Checksum',
  filename: 'Dosya',
  file: 'Dosya',
  gdpr: 'GDPR',
  pci: 'PCI',
  hipaa: 'HIPAA',
  'nist-800-53': 'NIST 800-53',
  cis: 'CIS',
  event: 'Olay',
  groups: 'Gruplar',
  name: 'Ad',
  count: 'Count',
  'details.program_name': 'Program Adı',
  'details.order': 'Order',
  vendor: 'Vendor',
  type: 'Type',
  architecture: 'Mimari',
  node_name: 'Node',
  dateAdd: 'Kayıt Tarihi',
  manager: 'Yönetici',
  lastKeepAlive: 'Son Aktivite',
  os: 'OS',
  path: 'Konum',
  details: 'Detaylar',
  position: 'Pozisyon',
  configSum: 'Grup checksum',
  mergedSum: 'Konfigürasyon checksum',
  key: 'Key',
  scan_id: 'Tarama ID',
  format: 'Format',
  scan_time: 'Tarama tarihi',
  state: 'State',
  mac: 'MAC',
  gateway: 'Gateway',
  dhcp: 'DHCP',
  iface: 'Interface',
  broadcast: 'Broadcast',
  proto: 'Protocol',
  address: 'Address',
  protocol: 'Protocol',
  netmask: 'Netmask',
  'local.ip': 'Lokal IP',
  'remote.ip': 'Uzak IP',
  'local.port': 'Lokal port',
  'remote.port': 'Uzak port',
  euser: 'Efektif kullanıcı',
  egroup: 'Efektif grup',
  vm_size: 'VM boyutu',
  processor: 'İşlemci',
  session: 'Oturum',
  tty: 'TTY',
  pid: 'PID',
  ppid: 'Parent PID',
  argvs: 'Argvs',
  nice: 'Priority',
  size: 'Boyut',
  uname: 'Kullanıcı',
  gname: 'Grup',
  perm: 'Yetkiler',
  inode: 'Inode',
  uid: 'Kullanıcı ID',
  gid: 'Grup ID',
  mtime: 'Son değiştirilme',
  priority: 'Priority',
  cmd: 'Komut',
  nlwp: 'NLWP',
  process: 'İşlem',
  md5: 'MD5',
  sha1: 'SHA1',
  sha256: 'SHA256',
  title: 'Başlık',
  remediation: 'Remediation',
  references: 'Referanslar',
  result: 'Sonuç',
  directory: 'Konum(lar)',
  rationale: 'Rationale',
  registry: 'Kayıt',
  date: 'Tarih',
  value: 'Değer',
  location: 'Konum',
  mtu: 'MTU',
  attributes: 'Attributes',
  policy_id: 'Policy ID',
  policy_ID: 'Policy ID',
  compliance: 'Compliance',
  rules: 'Kurallar',
  reason: 'Sebep',
  registerIP: 'Register IP',
  hotfix: 'Update code',
  'scan.time': 'Registered by Defans SIEM at'
};
